version: '3'
services:
  automation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bd-automation
    env_file:
      - .env
    networks:
        - botdetector-network
        
networks:
    botdetector-network:
