
name: Development workflow
on:
  push:
    branches: [ develop ]

jobs:
  setup:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set Up ENV
      run: |
          echo "${{secrets.EMAIL_FROM}}" > .env
          echo "${{secrets.EMAIL_TIPOFF}}" >> .env
          echo "${{secrets.SMTP_PASSWORD}}" >> .env
          echo "${{secrets.SMTP_PORT}}" >> .env
          echo "${{secrets.SMTP_SERVER}}" >> .env
          echo "${{secrets.JMOD_TAG}}" >> .env
          echo "${{secrets.SERVER_LOGIN}}" >> .env
          echo "${{secrets.SERVER_PASSWORD}}" >> .env
          echo "${{secrets.DATABASE}}" >> .env
          echo "${{secrets.SERVER_ADDRESS}}" >> .env
          echo "${{secrets.GRAVEYARD_WEBHOOK}}" >> .env
          echo "${{secrets.CONSUMER_KEY}}" >> .env
          echo "${{secrets.CONSUMER_SECRET}}" >> .env
          echo "${{secrets.BEARER_TOKEN}}" >> .env
          echo "${{secrets.ACCESS_TOKEN}}" >> .env
          echo "${{secrets.ACCESS_TOKEN_SECRET}}" >> .env

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t bot-detector/bd-automations:latest

    - name: Tag Image
      run: docker tag bot-detector/bd-automations:latest hub.osrsbotdetector.com/bot-detector/bd-automations:latest
      
    - name: Login to Docker Registry
      run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login https://hub.osrsbotdetector.com -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin

    - name: Push Image to Registry
      run: docker push hub.osrsbotdetector.com/bot-detector/bd-automations:latest

    - name: Apply Possible Deployment Changes
      run: kubectl apply -f deployment.yaml

    - name: Restart Deployment for Possible Container Changes
      run: kubectl rollout restart deploy bd-automations
